import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv(r"C:\Retail_Sales_Analysis\data\SampleSuperstore.csv\SampleSuperstore.csv")
print(df.head(5))
df.info()
print(df.isnull())
print(df.duplicated())
print(df.describe())
print("Total SALES of the Year",df["Sales"].sum())
print("Total PROFIT of the Year",df["Profit"].sum())
print("Avg SALES PER ORDER",df["Sales"].mean())
print("Avg PROFIT PER ORDER",df["Profit"].mean())
print("Total SALES FOR EACH CATEGORY",df.groupby("Category")["Sales"].sum())
print("Total SALES FOR EACH CATEGORY",df.groupby("Category")["Profit"].sum())
print("Average SALES FOR EACH CATEGORY",df.groupby("Category")["Sales"].mean())
print("Average PROFIT FOR EACH CATEGORY",df.groupby("Category")["Profit"].mean())
print("Total SALES FOR EACH SUB CATEGORY",df.groupby("Sub-Category")["Sales"].sum())
print("Total PROFIT FOR EACH SUB CATEGORY",df.groupby("Sub-Category")["Profit"].sum())
top=df.groupby("Sub-Category")["Sales"].sum()
profit=df.groupby("Sub-Category")["Profit"].sum()
state_sale=df.groupby("State")["Sales"].sum()
state_profit=df.groupby("State")["Profit"].sum()
print("TOP 10 SUB-CATEGORIES BY TOTAL SALES",top.sort_values(ascending=False).head(10))
print("TOP 10 SUB-CATEGORIES BY TOTAL PROFIT",profit.sort_values(ascending=False).head(10))
print("TOP 10 STATES BY TOTAL SALES",state_sale.sort_values(ascending=False).head(10))
print("TOP 10 STATES BY TOTAL PROFIT",state_profit.sort_values(ascending=False).head(10))
print("Total SALES FOR EACH REGIION",df.groupby("Region")["Sales"].sum())
print("Total PROFIT FOR EACH REGIION",df.groupby("Region")["Profit"].sum())
print("Total SALES FOR EACH CUSTOMER SEGMENT",df.groupby("Segment")["Sales"].sum())
print("Total PROFIT FOR EACH CUSTOMER SEGMENT",df.groupby("Segment")["Sales"].sum())
print("Average PROFIT FOR EACH CUSTOMER SEGMENT",df.groupby("Segment")["Sales"].mean())
top_cities=df.groupby("Sub-Category")["Sales"].sum()
print("TOP 10 CITIES BY TOTAL SALES",top_cities.sort_values(ascending=False).head(10))
print("TOP 10 CITIES BY TOTAL PROFIT",df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending=False).head(10))
print("Total ITEMS SOLD FOR EACH SUB CATEGORY",df.groupby("Sub-Category")["Quantity"].sum())
print("Total ITEMS SOLD FOR EACH REEGION",df.groupby("Region")["Quantity"].sum())
top_category=df.groupby("Category")["Sales"].sum()
print("CATEGORY WITH THE HIGHEST TOTALL SALES",top_category.head(1))
print("CATEGORY WITH THE LOWEST TOTALL SALES",top_category.tail(1))
top_category_profit=df.groupby("Category")["Profit"].sum()
print("CATEGORY WITH THE HIGHEST TOTALL PROFIT",top_category_profit.head(1))
print("CATEGORY WITH THE LOWEST TOTALL PROFIT",top_category_profit.tail(1))
region=df.groupby("Region")["Profit"].sum()
print("REGION WITH THE HIGHEST TOTALL PROFIT",top_category_profit.head(1))
print("REGION WITH THE LOWEST TOTALL PROFIT",top_category_profit.tail(1))
print("CORELATION",df.corr(numeric_only=True))
plt.figure(figsize=(6,4))
plt.bar(top_category_profit.index,top_category_profit.values,color='red',width=0.4)
plt.title('TOTAL PROFIT FOR EACH CATEGORY')
plt.xlabel('Category')
plt.ylabel('Profit')
plt.grid(linewidth=0.4)
plt.savefig("images/profit_by_category_bar.png")
plt.show()
region_sale=df.groupby("Region")["Sales"].sum()
plt.figure(figsize=(6,4))
plt.bar(region_sale.index,region_sale.values,color='magenta',width=0.4)
plt.title('TOTAL SALES FOR EACH REGION')
plt.xlabel('Region')
plt.ylabel('Sales')
plt.grid(linewidth=0.4)
plt.savefig("images/sales_by_region_bar.png")
plt.show()
plt.figure(figsize=(6,4))
plt.bar(region.index,region.values,color='coral',width=0.4)
plt.title('TOTAL PROFIT FOR EACH REGION')
plt.xlabel('Region')
plt.ylabel('Profit')
plt.grid(linewidth=0.4)
plt.savefig("images/profit_by_region_bar.png")
plt.show()
sub_cat=df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(6,4))
plt.barh(sub_cat.index,sub_cat.values,color='olive')
plt.title('TOP 10 SUB CATEGORIES BY TOTAL SALES')
plt.ylabel('Sub Category')
plt.xlabel('Sales')
plt.grid(linewidth=0.4)
plt.savefig("images/top10_subcategories_sales.png")
plt.show()
plt.figure(figsize=(6,4))
plt.plot(top_category.index,top_category.values,marker='o')
plt.title('TOTAL SALES FOR EACH CATEGORY')
plt.xlabel('Category')
plt.ylabel('Sales')
plt.grid(linewidth=0.4)
plt.savefig("images/sales_by_category_line.png")
plt.show()
plt.figure(figsize=(6,4))
plt.plot(top_category_profit.index,top_category_profit.values,color='red',marker='o')
plt.title('TOTAL PROFIT FOR EACH CATEGORY')
plt.xlabel('Category')
plt.ylabel('Profit')
plt.grid(linewidth=0.4)
plt.savefig("images/profit_by_category_line.png")
plt.show()
plt.figure(figsize=(6,4))
plt.pie(top_category.values,labels=top_category.index,colors=['pink','yellow','olive'],autopct='%1.1f%%')
plt.title('TOTAL SALES FOR EACH CATEGORY')
plt.savefig("images/sales_by_category_pie.png")
plt.show()
plt.figure(figsize=(6,4))
plt.pie(top_category_profit.values,labels=top_category_profit.index,colors=['skyblue','lightgreen','salmon'],autopct='%1.1f%%')
plt.title('TOTAL PROFIT FOR EACH CATEGORY')
plt.savefig("images/profit_by_category_pie.png")
plt.show()
plt.figure(figsize=(6,4))
plt.hist(df["Sales"],bins=5,color='salmon',edgecolor='blue')
plt.xlabel('Sales Range')
plt.ylabel('No of Sales')
plt.title("DISTRIBUTION OF SALES")
plt.savefig("images/sales_distribution.png")
plt.show()
plt.figure(figsize=(6,4))
plt.boxplot(df["Sales"])
plt.title('BOX PLOT OF SALES')
plt.ylabel('Sales')
plt.savefig("images/sales_boxplot.png")
plt.show()
sns.scatterplot(data=df,x='Sales',y='Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.title('RELATIONSHIP BETWEEN SALES AND PROFIT')
plt.savefig("images/sales_vs_profit_scatter.png")
plt.show()
plt.figure(figsize=(6,4))
sns.heatmap(data=df[["Sales","Profit","Quantity","Discount"]].corr(),annot=True)
plt.title('CORRELATION HEATMAP')
plt.savefig("images/correlation_heatmap.png")
plt.show()
sns.countplot(data=df,x='Category',color='lightblue')
plt.title('NUMBER OF RECORDS IN EACH CATEGORY')
plt.savefig("images/category_countplot.png")
plt.show()
plt.figure(figsize=(6,4))
g=sns.pairplot(df[["Sales","Profit","Quantity","Discount"]])
g.fig.suptitle("PAIR PLOT OF SALES,PROFIT,QUANTITY AND DISCOUNT",y=1.02)
g.savefig("images/pair_plot.png")
plt.show()

